package com.bookshelf.controller;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;

import java.util.Iterator;
import java.util.Map;
import java.util.UUID;

/**
 * Generates a downloadable Insomnia v4 collection from the live OpenAPI spec.
 *
 * How it works:
 *  1. Makes a self-call to /v3/api-docs to get the current OpenAPI JSON
 *  2. Iterates every path + HTTP method from that spec
 *  3. Transforms each into an Insomnia "request" resource
 *  4. Wraps everything in an Insomnia v4 export envelope (workspace + environment + requests)
 *  5. Returns the JSON as a downloadable file attachment
 *
 * The collection stays in sync automatically — any new endpoint annotated
 * with @Operation will appear in the next download without changes here.
 */
@RestController
@RequestMapping("/api/collection")
@Tag(name = "API Collection", description = "Export API endpoints as an Insomnia collection")
public class ApiCollectionController {

    // Jackson's ObjectMapper — converts Java objects <-> JSON and builds JSON trees programmatically
    private final ObjectMapper objectMapper;

    public ApiCollectionController(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    @Operation(summary = "Download Insomnia collection")
    @GetMapping(value = "/insomnia", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> exportInsomniaCollection() throws Exception {

        // --- Step 1: Fetch our own OpenAPI spec ---
        // RestTemplate makes an HTTP GET to this same server's /v3/api-docs endpoint.
        // This returns the full OpenAPI 3.0 JSON generated by springdoc from our @Operation annotations.
        RestTemplate restTemplate = new RestTemplate();
        String openApiJson = restTemplate.getForObject(
                "http://localhost:8080/v3/api-docs", String.class);

        // Parse the raw JSON string into a traversable Jackson tree (JsonNode)
        JsonNode openApi = objectMapper.readTree(openApiJson);

        // --- Step 2: Build the Insomnia v4 export envelope ---
        // Insomnia expects: { _type: "export", __export_format: 4, resources: [...] }
        ObjectNode export = objectMapper.createObjectNode();
        export.put("_type", "export");
        export.put("__export_format", 4);           // Insomnia v4 format version
        export.put("__export_source", "bookshelf-api"); // identifies where the export came from

        // resources[] holds every item: workspace, environment, and individual requests
        ArrayNode resources = objectMapper.createArrayNode();

        // --- Step 3: Create the workspace ---
        // A workspace is the top-level container in Insomnia (like a project folder).
        // All requests and environments are children of this workspace via parentId.
        String workspaceId = "wrk_bookshelf";
        ObjectNode workspace = objectMapper.createObjectNode();
        workspace.put("_id", workspaceId);
        workspace.put("_type", "workspace");
        workspace.put("name", "BookShelf API");
        resources.add(workspace);

        // --- Step 4: Create the base environment ---
        // Environments hold reusable variables. Here we define {{ base_url }}
        // so every request uses it instead of a hardcoded host.
        // Users can override this in Insomnia to point to staging/production.
        ObjectNode env = objectMapper.createObjectNode();
        env.put("_id", "env_bookshelf");
        env.put("_type", "environment");
        env.put("parentId", workspaceId);            // belongs to the workspace above
        env.put("name", "Base Environment");
        ObjectNode envData = objectMapper.createObjectNode();
        envData.put("base_url", "http://localhost:8080"); // default dev server URL
        env.set("data", envData);
        resources.add(env);

        // --- Step 5: Convert each OpenAPI path + method into an Insomnia request ---
        // OpenAPI structure: { paths: { "/api/books": { "get": {...}, "post": {...} } } }
        // We iterate the outer map (paths) then the inner map (HTTP methods per path).
        JsonNode paths = openApi.get("paths");
        if (paths != null) {
            Iterator<Map.Entry<String, JsonNode>> pathIter = paths.fields();
            while (pathIter.hasNext()) {
                Map.Entry<String, JsonNode> pathEntry = pathIter.next();
                String path = pathEntry.getKey();       // e.g. "/api/books/{bookId}"
                JsonNode methods = pathEntry.getValue(); // e.g. { "get": {...}, "delete": {...} }

                Iterator<Map.Entry<String, JsonNode>> methodIter = methods.fields();
                while (methodIter.hasNext()) {
                    Map.Entry<String, JsonNode> methodEntry = methodIter.next();
                    String method = methodEntry.getKey().toUpperCase(); // "get" -> "GET"
                    JsonNode operation = methodEntry.getValue();        // the operation object with summary, parameters, etc.

                    ObjectNode request = objectMapper.createObjectNode();
                    // Generate a unique ID per request (req_ + 8-char UUID fragment)
                    request.put("_id", "req_" + UUID.randomUUID().toString().substring(0, 8));
                    request.put("_type", "request");
                    request.put("parentId", workspaceId); // all requests live under the workspace

                    // Use the @Operation(summary) as the display name, fallback to "GET /api/books"
                    request.put("name", operation.has("summary")
                            ? operation.get("summary").asText()
                            : method + " " + path);
                    request.put("method", method);

                    // {{ base_url }} references the environment variable defined above
                    request.put("url", "{{ base_url }}" + path);

                    // Default Content-Type header for all requests
                    ArrayNode headers = objectMapper.createArrayNode();
                    ObjectNode contentType = objectMapper.createObjectNode();
                    contentType.put("name", "Content-Type");
                    contentType.put("value", "application/json");
                    headers.add(contentType);
                    request.set("headers", headers);

                    resources.add(request);
                }
            }
        }

        // Attach all resources (workspace + environment + requests) to the export envelope
        export.set("resources", resources);

        // Pretty-print the JSON for readability when opened in a text editor
        String result = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(export);

        // Return as a downloadable file attachment
        // Content-Disposition: attachment triggers browser download instead of displaying inline
        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=\"bookshelf-api-insomnia.json\"")
                .contentType(MediaType.APPLICATION_JSON)
                .body(result);
    }
}
